---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: {{ .Values.namespace }}
  labels:
    name: postgres-service
    app: demo-voting-app
spec:
  ports:
  - port: {{ .Values.services.postgres.port }}
    targetPort: {{ .Values.services.postgres.targetPort }}
  selector:
    name: postgres-pod
    app: demo-voting-app
