---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  namespace: {{ .Values.namespace }}
  labels:
    name: postgres-deploy
    app: demo-voting-app
spec:
  replicas: {{ .Values.deployments.postgres.replicas }}
  selector:
    matchLabels:
      name: postgres-pod
      app: demo-voting-app
  template:
    metadata:
      name: postgres-pod
      labels:
        name: postgres-pod
        app: demo-voting-app
    spec:
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: {{ .Values.envs.postgres.POSTGRES_USER }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.envs.postgres.POSTGRES_PASSWORD }}
          - name: POSTGRES_HOST_AUTH_METHOD
            value: {{ .Values.envs.postgres.POSTGRES_HOST_AUTH_METHOD }}
