---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: {{ .Values.namespace }}
  labels:
    name: redis-service
    app: demo-voting-app
spec:
  ports:
  - port: {{ .Values.services.redis.port }}
    targetPort: {{ .Values.services.redis.targetPort }}
  selector:
    name: redis-pod
    app: demo-voting-app
