---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app-deploy
  namespace: {{ .Values.namespace }}
  labels:
    name: result-app-deploy
    app: demo-voting-app
spec:
  replicas: {{ .Values.deployments.resultApp.replicas }}
  selector:
    matchLabels:
      name: result-app-pod
      app: demo-voting-app
  template:
    metadata:
      name: result-app-pod
      labels:
        name: result-app-pod
        app: demo-voting-app
    spec:
      containers:
      - name: result-app
        image: {{ .Values.deployments.resultApp.image }}
        ports:
        - containerPort: {{ .Values.deployments.resultApp.containerPort }}