---
apiVersion: v1
kind: Service
metadata:
  name: voting-service
  namespace: {{ .Values.namespace }}
  labels:
    name: voting-service
    app: demo-voting-app
spec:
  type: NodePort
  ports:
  - port: {{ .Values.services.votingApp.port }}
    targetPort: {{ .Values.services.votingApp.targetPort }}
    nodePort: {{ .Values.services.votingApp.nodePort }}
  selector:
    name: voting-app-pod
    app: demo-voting-app
